In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2022-09-12 10:19:30--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8003::154, 2606:50c0:8000::154, 2606:50c0:8002::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8003::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1,4M) [text/plain]
Saving to: ‘data.csv.2’

data.csv.2          100%[===================>]   1,41M  3,20MB/s    in 0,4s    

2022-09-12 10:19:31 (3,20 MB/s) - ‘data.csv.2’ saved [1475504/1475504]



# Question 1

In [4]:
np.version.version

'1.21.5'

# Question 2

In [20]:
df = pd.read_csv('data.csv.1')
print("len: ", len(df));

len:  11914


# Question 3

In [21]:
df['Make'].value_counts().head(5)

Chevrolet     1123
Ford           881
Volkswagen     809
Toyota         746
Dodge          626
Name: Make, dtype: int64

# Question 4

In [25]:

df[
    df['Make'] == 'Audi'
  ].Model.nunique()


34

# Question 5

In [30]:
len(df.isna().sum()[df.isna().sum() > 0])

5

# Question 6

In [31]:
df['Engine Cylinders'].median()

6.0

In [32]:
df['Engine Cylinders'].mode()[0]

4.0

In [33]:
df['Engine Cylinders'].fillna(df['Engine Cylinders'].mode()[0], inplace=True)

In [34]:
df['Engine Cylinders'].median()

6.0

# Question 7

In [35]:
df2 = df.loc[df['Make'] == 'Lotus']

In [36]:
df2 = df2[["Engine HP", "Engine Cylinders"]]

In [37]:
df2.drop_duplicates(inplace=True, ignore_index=True)
df2

Engine HP  Engine Cylinders
0      189.0               4.0
1      218.0               4.0
2      217.0               4.0
3      350.0               8.0
4      400.0               6.0
5      276.0               6.0
6      345.0               6.0
7      257.0               4.0
8      240.0               4.0

In [38]:
X = df2.values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [39]:
XTX = X.T.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [40]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [41]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [42]:
w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

In [43]:
w[0]

4.594944810094551